# Generated by Django 4.2.1 on 2023-07-04 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('journal_no', models.CharField(max_length=255)),
                ('reference_no', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.CharField(max_length=255)),
                ('cash_journal', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, upload_to='attachments/')),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=200)),
                ('debits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.journal')),
            ],
        ),
    ]
