# Generated by Django 4.2.1 on 2023-07-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_journal_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
